### ISSUE TITLE
"Getting Started" link on site leads to 404

### ISSUE THREAD

**Issue by mrdziuban** [sagifogel/Proptics#333]
Hi, I'm interested in learning more about this library and profunctor optics in general so was hoping to read the docs but the "Getting Started" link on the site leads to this 404 page: https://sagifogel.github.io/Proptics/docs/overview

I see that the docs are all available here in the repo, but I'm not exactly sure where to start or what order to read through them in.

Thanks in advance!

**Comment by sagifogel** [comment]
Hi Matt.
Thanks for expressing interest in `Proptics`, and sorry for the really late response. 
Recently I saw that the documentation was broken.
I will fix it soon and send you a message
Thank you,
Sagi

**Comment by sagifogel** [comment]
fixed
cc: @mrdziuban
